### ISSUE TITLE
Version 4.15.7 not installing on remote machine

### ISSUE THREAD

**Issue by VassiliYakovlev** [mjcrouch/vscode-perforce#280]
**Describe the bug:**

Version v4.15.7 not installing on remote Linux machine via SSH.

**Expected behavior:**

**To Reproduce:**

**Versions & Details:**
 - Perforce extension:  v4.15.7
 - VSCode version:  1.91.1
 - Operating System: Local: Windows 10; Remote: RH Enterprise 8.4
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: Yes/No

**Additional context**

<details>

2024-07-19 12:23:38.726 [error] Error: Unable to read file '/home/***/.vscode-server/extensions/mjcrouch.perforce-4.15.7/package.json' (Error: Unable to resolve nonexistent file '/home/***/.vscode-server/extensions/mjcrouch.perforce-4.15.7/package.json')
    at t.F (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:120:17539)
    at t.D (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:120:17334)
    at async t.C (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:120:16646)
    at async a.updateMetadata (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:174:52043)
    at async B.extractUserExtension (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:174:84796)
    at async z.pb (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:174:79163)
2024-07-19 12:23:38.753 [error] Unable to read file '/home/***/.vscode-server/extensions/mjcrouch.perforce-4.15.7/package.json' (Error: Unable to resolve nonexistent file '/home/***/.vscode-server/extensions/mjcrouch.perforce-4.15.7/package.json'): Error: Unable to read file '/home/***/.vscode-server/extensions/mjcrouch.perforce-4.15.7/package.json' (Error: Unable to resolve nonexistent file '/home/***/.vscode-server/extensions/mjcrouch.perforce-4.15.7/package.json')
    at t.F (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:120:17539)
    at t.D (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:120:17334)
    at async t.C (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:120:16646)
    at async a.updateMetadata (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:174:52043)
    at async B.extractUserExtension (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:174:84796)
    at async z.pb (/tmp/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/out/vs/server/node/server.main.js:174:79163)

</details>

**Comment by mjcrouch** [comment]
Hi - thanks for reporting.
The extension itself doesn't have any part in the install process - it looks like the error is with vscode or vscode-server so  would need to be reported there

**Comment by mjcrouch** [comment]
it's been quite a long time since I've used vs code remotely. Have you tried manually deleting the /home//.vscode-server/extensions/mjcrouch.perforce-4.15.7/ directory before doing the install again?

**Comment by VassiliYakovlev** [comment]
Thank you for the advise. It worked. I didn't realized that it might be the issue.
