### ISSUE TITLE
Language server error when using perforce extension

### ISSUE THREAD

**Issue by AbsolutelySimonW** [mjcrouch/vscode-perforce#289]
**Describe the bug:**
When installing the perforce extension or opening VSCode with the extension installed, the following error appears:

![image](https://github.com/user-attachments/assets/34bf6bb6-bbfc-429e-b0f4-aade2857ff8b)

**Expected behavior:**
Language server should not crash

**To Reproduce:**
Install the following VS extensions and open any c# file

![image](https://github.com/user-attachments/assets/708d673c-f614-4210-ad6f-97d22e1eed91)

**Versions & Details:**
 - Perforce extension: tested 4.15.7 and 4.16.0
 - VSCode version: tested 1.95.2 and 1.96.0 insider
 - Operating System: Windows 11
 - Perforce server details (if known):
 - Are you using a multi-root workspace?: No

**Additional context**

<details>

```
P4 Output

Performing one-time registration of perforce commands
==============================
Workspace folders changed. Starting initialisation.

Workspaces were added
> file:///c%3A/Dev/Project: Trying to initialise SCM Providers in this workspace.
	Note: the following overrides apply in this workspace:
		perforce.port: none	(will not override)
		perforce.user: none	(will not override)
		perforce.client: none	(will not override)
		perforce.dir: none	(will not override)
	Explicit overrides may prevent auto-detection of other perforce client workspaces
Looking for a client root using the workspace root directory
c:\Dev\Project: p4.exe 'info'
> file:///c%3A/Dev/Project: Found workspace using root directory
  * VS Code workspace root directory :
	Client name: simonwatson_Laptop_Project
	Client root: c:\Dev\Project
	User name: simonwatson
	Server address: fra-fs3:2453
	Folder IS in or above client root
> file:///c%3A/Dev/Project: Looking for perforce config files
c:\Dev\Project: p4.exe 'set' '-q'
> file:///c%3A/Dev/Project: Using pattern **/p4config.txt
> file:///c%3A/Dev/Project: Found 1 config file(s)
> file:///c%3A/Dev/Project: Finding client roots using each file's directory
c:\Dev\Project: p4.exe 'info'
> file:///c%3A/Dev/Project: Found the following roots from the location of 1 P4CONFIG file(s):
  * c:\Dev\Project\p4config.txt :
	Client name: simonwatson_Laptop_Project
	Client root: c:\Dev\Project
	User name: simonwatson
	Server address: fra-fs3:2453
	Folder IS in or above client root
> file:///c%3A/Dev/Project: Creating SCM provider for simonwatson_Laptop_Project @ c:\Dev\Project because of source : c:\Dev\Project
> file:///c%3A/Dev/Project: SCM provider already exists for simonwatson_Laptop_Project @ c:\Dev\Project - not creating another for source : c:\Dev\Project
> file:///c%3A/Dev/Project: Initialisation done for this workspace. Created 1 provider(s), ignored 1 duplicate(s)



Initialisation finished
==============================

c:\Dev\Project: p4.exe 'login' '-s'
c:\Dev\Project: p4.exe 'login' '-s'
c:\Dev\Project: p4.exe 'changes' '-l' '-c' 'simonwatson_Laptop_Project' '-s' 'pending'
c:\Dev\Project: p4.exe 'describe' '-S' '-s' '393' '381'
c:\Dev\Project: p4.exe 'opened'
c:\Dev\Project: p4.exe 'fstat' '-Or' '//depot/main/Assets/Game/DevArt/RenderTextures/CharacterVisualisation0.renderTexture' '//depot/main/Assets/Game/DevArt/RenderTextures/CharacterVisualisation1.renderTexture' '//depot/main/Assets/Game/DevArt/RenderTextures/CharacterVisualisation2.renderTexture' '//depot/main/Assets/Game/DevArt/RenderTextures/CharacterVisualisation3.renderTexture' '//depot/main/Assets/Game/Prefabs/UI/Panels/AttackBarPanel.prefab' '//depot/main/Assets/Resources/DOTweenSettings.asset' '//depot/main/Assets/StreamingAssets/BalanceSheets/CellEntityClasses/GruntClass' '//depot/main/Assets/StreamingAssets/BalanceSheets/CellEntityClasses/GruntClass.meta' '//depot/main/Assets/StreamingAssets/BalanceSheets/Classes/Grunt' '//depot/main/Assets/StreamingAssets/BalanceSheets/Classes/Grunt.meta' '//depot/main/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset'
c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities: p4.exe 'opened' 'c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities\MeleeWeaponAbility.cs'
c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities: p4.exe 'have' 'c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities\MeleeWeaponAbility.cs'
c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities: p4.exe 'print' '-q' 'c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities\MeleeWeaponAbility.cs#have'
\: p4.exe 'opened' 'extension-output-ms-dotnettools.vscode-dotnet-runtime-%231-.NET Install Tool'
c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities: p4.exe 'opened' 'c:\Dev\Project\Assets\Game\GitManaged\Scripts\InMission\Units\Abilities\WeaponAbilities\MeleeWeaponAbilities\MeleeWeaponAbility.cs'
\: p4.exe 'opened' 'extension-output-mjcrouch.perforce-%231-Perforce Log'

```
```
C# Output

2024-11-13 16:42:40.218 [info] Using dotnet configured on PATH
2024-11-13 16:42:40.220 [info] Dotnet path: C:\Program Files\dotnet\dotnet.exe
2024-11-13 16:42:40.220 [info] Activating C# + C# Dev Kit...
2024-11-13 16:42:41.600 [info] [stdout] {"pipeName":"\\\\.\\pipe\\66dd7d5d"}

2024-11-13 16:42:41.600 [info] received named pipe information from server
2024-11-13 16:42:41.601 [info] client has connected to server
2024-11-13 16:42:41.949 [info] [Info  - 4:42:41 PM] [Program] Language server initialized
2024-11-13 16:42:48.256 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\Assembly-CSharp-firstpass.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.260 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\Assembly-CSharp.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.263 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\AGCore.Editor.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.266 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\AGCore.Runtime.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.267 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\Assembly-CSharp-Editor-firstpass.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.267 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\ZString.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.268 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\UIEffect.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.269 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\UIEffect-Editor.csproj loaded by C# Dev Kit
2024-11-13 16:42:48.269 [info] [Info  - 4:42:48 PM] [WorkspaceProjectFactoryService] Project C:\Dev\Project\Assembly-CSharp-Editor.csproj loaded by C# Dev Kit
2024-11-13 16:44:47.806 [info] [Error - 4:44:47 PM] [LanguageServerHost] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Roslyn.LanguageServer.Protocol.DocumentUriConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/LanguageServer/Protocol/Protocol/Converters/DocumentUriConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.DeserializeRequest[TRequest](Object serializedRequest, RequestHandlerMetadata metadata) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 30
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.TryDeserializeRequest[TRequest](AbstractLanguageServer`1 languageServer, RequestHandlerMetadata requestHandlerMetadata, Boolean isMutating, TRequest& request) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 120
2024-11-13 16:44:47.807 [info] [Error - 4:44:47 PM] [LanguageServerHost] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Roslyn.LanguageServer.Protocol.DocumentUriConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/LanguageServer/Protocol/Protocol/Converters/DocumentUriConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.DeserializeRequest[TRequest](Object serializedRequest, RequestHandlerMetadata metadata) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 30
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.TryDeserializeRequest[TRequest](AbstractLanguageServer`1 languageServer, RequestHandlerMetadata requestHandlerMetadata, Boolean isMutating, TRequest& request) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 120
--- End of stack trace from previous location ---
   at Microsoft.CommonLanguageServerProtocol.Framework.AbstractLanguageServer`1.DelegatingEntryPoint.InvokeAsync(IRequestExecutionQueue`1 queue, Object requestObject, ILspServices lspServices, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs:line 204
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.SystemTextJsonDelegatingEntryPoint.ExecuteRequestAsync(Nullable`1 request, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 88
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.CreateRequestContextAsync[TRequest](IMethodHandler handler, RequestHandlerMetadata requestHandlerMetadata, AbstractLanguageServer`1 languageServer, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueCoreAsync[TRequest,TResponse](IQueueItem`1 work, IMethodHandler handler, RequestHandlerMetadata metadata, ConcurrentDictionary`2 concurrentlyExecutingTasks, CancellationTokenSource currentWorkCts, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.InvokeProcessCoreAsync(IQueueItem`1 work, RequestHandlerMetadata metadata, IMethodHandler handler, MethodInfo methodInfo, ConcurrentDictionary`2 concurrentlyExecutingTasks, CancellationTokenSource currentWorkCts, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 320
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync() in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 272
2024-11-13 16:44:47.808 [info] [Info  - 4:44:47 PM] Error processing queue, shutting down
2024-11-13 16:44:47.818 [info] [Error - 4:44:47 PM] Workspace diagnostic pull failed.
2024-11-13 16:44:47.818 [info] Canceled: Canceled
    at a.handleFailedRequest (c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:2129731)
    at a.handleFailedRequest (c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:1164702)
    at c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:2167141
    at g.pullWorkspaceAsync (c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:2164449)
2024-11-13 16:44:47.834 [info] [Info  - 4:44:47 PM] Connection to server got closed. Server will restart.
2024-11-13 16:44:47.834 [info] true
2024-11-13 16:44:48.173 [info] Using dotnet configured on PATH
2024-11-13 16:44:48.174 [info] Dotnet path: C:\Program Files\dotnet\dotnet.exe
2024-11-13 16:44:48.174 [info] Activating C# + C# Dev Kit...
2024-11-13 16:44:48.285 [info] [stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\.xamlTools\Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\.xamlTools\Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\.xamlTools

2024-11-13 16:44:48.824 [info] [stdout] {"pipeName":"\\\\.\\pipe\\12c3ab24"}

2024-11-13 16:44:48.824 [info] received named pipe information from server
2024-11-13 16:44:48.824 [info] client has connected to server
2024-11-13 16:44:48.881 [info] [Info  - 4:44:48 PM] [Program] Language server initialized
2024-11-13 16:44:49.211 [info] [Error - 4:44:49 PM] [LanguageServerHost] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Roslyn.LanguageServer.Protocol.DocumentUriConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/LanguageServer/Protocol/Protocol/Converters/DocumentUriConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.DeserializeRequest[TRequest](Object serializedRequest, RequestHandlerMetadata metadata) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 50
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.TryDeserializeRequest[TRequest](AbstractLanguageServer`1 languageServer, RequestHandlerMetadata requestHandlerMetadata, Boolean isMutating, TRequest& request) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 120
2024-11-13 16:44:49.213 [info] [Error - 4:44:49 PM] [LanguageServerHost] System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Roslyn.LanguageServer.Protocol.DocumentUriConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/LanguageServer/Protocol/Protocol/Converters/DocumentUriConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.DeserializeRequest[TRequest](Object serializedRequest, RequestHandlerMetadata metadata) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 50
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.TryDeserializeRequest[TRequest](AbstractLanguageServer`1 languageServer, RequestHandlerMetadata requestHandlerMetadata, Boolean isMutating, TRequest& request) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 120
--- End of stack trace from previous location ---
   at Microsoft.CommonLanguageServerProtocol.Framework.AbstractLanguageServer`1.DelegatingEntryPoint.InvokeAsync(IRequestExecutionQueue`1 queue, Object requestObject, ILspServices lspServices, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/AbstractLanguageServer.cs:line 204
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.SystemTextJsonDelegatingEntryPoint.ExecuteRequestAsync(Nullable`1 request, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 88
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.CreateRequestContextAsync[TRequest](IMethodHandler handler, RequestHandlerMetadata requestHandlerMetadata, AbstractLanguageServer`1 languageServer, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueCoreAsync[TRequest,TResponse](IQueueItem`1 work, IMethodHandler handler, RequestHandlerMetadata metadata, ConcurrentDictionary`2 concurrentlyExecutingTasks, CancellationTokenSource currentWorkCts, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 337
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.InvokeProcessCoreAsync(IQueueItem`1 work, RequestHandlerMetadata metadata, IMethodHandler handler, MethodInfo methodInfo, ConcurrentDictionary`2 concurrentlyExecutingTasks, CancellationTokenSource currentWorkCts, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 320
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync() in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 272
2024-11-13 16:44:49.214 [info] [Info  - 4:44:49 PM] Error processing queue, shutting down
2024-11-13 16:44:49.215 [info] [Error - 4:44:49 PM] Workspace diagnostic pull failed.
2024-11-13 16:44:49.215 [info] Canceled: Canceled
    at a.handleFailedRequest (c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:2129731)
    at a.handleFailedRequest (c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:1164702)
    at c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:2167141
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processImmediate (node:internal/timers:454:9)
    at g.pullWorkspaceAsync (c:\Users\simon\.vscode-insiders\extensions\ms-dotnettools.csharp-2.55.28-win32-x64\dist\extension.js:2:2164449)
2024-11-13 16:44:49.219 [info] [Error - 4:44:49 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
2024-11-13 16:44:49.220 [info] [Error - 4:44:49 PM] Client Microsoft.CodeAnalysis.LanguageServer: connection to server is erroring. Shutting down server.
2024-11-13 16:44:49.220 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.220 [info]   Message: write EOF
  Code: -32099 
2024-11-13 16:44:49.220 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/ToolAbilities/TailNailAbility.cs
2024-11-13 16:44:49.220 [info]   Message: write EOF
  Code: -32099 
2024-11-13 16:44:49.221 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.221 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.221 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/WeaponAbilities/MeleeWeaponAbilities/MeleeWeaponAbility.cs
2024-11-13 16:44:49.221 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.221 [info] [Error - 4:44:49 PM] Connection to server got closed. Server will not be restarted.
2024-11-13 16:44:49.223 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.223 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.223 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/ToolAbilities/TailNailAbility.cs
2024-11-13 16:44:49.223 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.223 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.223 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.224 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/WeaponAbilities/MeleeWeaponAbilities/MeleeWeaponAbility.cs
2024-11-13 16:44:49.224 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.224 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.224 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.224 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/ToolAbilities/TailNailAbility.cs
2024-11-13 16:44:49.224 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.225 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.225 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.225 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/WeaponAbilities/MeleeWeaponAbilities/MeleeWeaponAbility.cs
2024-11-13 16:44:49.225 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.225 [info] [Error - 4:44:49 PM] Request textDocument/diagnostic failed.
2024-11-13 16:44:49.226 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.226 [info] [Error - 4:44:49 PM] Document pull failed for text document file:///c%3A/Dev/Project/Assets/Game/GitManaged/Scripts/InMission/Units/Abilities/ToolAbilities/TailNailAbility.cs
2024-11-13 16:44:49.226 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.237 [info] [Error - 4:44:49 PM] Stopping server failed
2024-11-13 16:44:49.237 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.237 [info] [Error - 4:44:49 PM] Stopping server failed
2024-11-13 16:44:49.237 [info]   Message: This socket has been ended by the other party
  Code: -32099 
2024-11-13 16:44:49.237 [info] [Error - 4:44:49 PM] Stopping server failed
2024-11-13 16:44:49.237 [info]   Message: This socket has been ended by the other party
  Code: -32099 

```

</details>

**Comment by mjcrouch** [comment]
Thanks for reporting, this is the same as #260 so closing as a duplicate - I believe I have a working fix for the issue
